// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class setNameOfMemberShipType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(setNameOfMemberShipType));
        
        string IMigrationMetadata.Id
        {
            get { return "201803250216551_setNameOfMemberShipType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
